Move `static_config` and `cpu_count` from R
ANLAB-KAIST/rust-static-config pull request #1
Opened 2020-05-20 10:15 UTC by leeopop

2020-05-20 10:15 UTC, leeopop commented
bors try

2020-05-20 10:17 UTC, leeopop commented
bors r+
(will fail)

2020-05-20 10:17 UTC, leeopop commented
bors r-

2020-05-20 11:25 UTC, jeehoonkang requested changes

2020-05-20 11:25 UTC, jeehoonkang commented on Cargo.toml
> +authors = ["Keunhong Lee <dlrmsghd@gmail.com>", "ANLAB Support <support@an.kaist.ac.kr>"]
"ANLAB Support" is an author?

2020-05-20 11:25 UTC, jeehoonkang commented on build.rs
> +/// 1. If `SYSTEM_CPU_COUNT` env is set, use this value.
이 기능을 지원하는건 좀 overspec이 아닌가 합니다. 그냥 무조건 num_cpus에서 넘버 가지고 오는게 어떨지?

2020-05-20 11:25 UTC, jeehoonkang commented on build.rs
> +        .write_fmt(format_args!("pub const CPU_COUNT: usize = {};", cpu_count))
- 혹시 좀더 덜 fragile한 방법은 있을지 궁금합니다.  Compile 시점 constant를 만드는 좀더 세련된? 방법이 있을까요?
- 없다면 이게 최선이라는 document를 찾아 주석으로 남겨주시길 부탁드려요

2020-05-20 11:25 UTC, jeehoonkang commented on build.rs
> +        let is_end = out_dir.file_name().unwrap() == "target";
이 로직이 올바른지 확신이 잘 안드는데.. 문서를 refer하면 좋ㄱㅆ어요

2020-05-20 11:25 UTC, jeehoonkang commented on build.rs
> +            if let Some((_prefix, _current)) = queue.pop_front() {
`let (current, prefix) = some_or!(queue.pop_front(), break);`

`let x;` 와 같이 decl만 하는걸 최대한 지양하길 바랍니다

2020-05-20 11:25 UTC, jeehoonkang commented
제가 좀 잔소리가 많은데..  이 crate은 비교적 API가 잘 정의되어 있으므로 그냥 머지해도 큰 문제는 없을 것 같아요  근홍님이 판단하시고 적당히 머지해주세요

2020-05-20 12:38 UTC, leeopop commented on build.rs
> +/// 1. If `SYSTEM_CPU_COUNT` env is set, use this value.
num cpu에서 가져오면 그 값으로 fixed length array를 만들 수 없습니다.

2020-05-21 08:50 UTC, leeopop commented on Cargo.toml
> +authors = ["Keunhong Lee <dlrmsghd@gmail.com>", "ANLAB Support <support@an.kaist.ac.kr>"]
https://doc.rust-lang.org/cargo/reference/manifest.html#the-authors-field

organization 도 적는 것 같아서 냅두도록 하겠습니다.

2020-05-21 08:54 UTC, leeopop commented on build.rs
> +        .write_fmt(format_args!("pub const CPU_COUNT: usize = {};", cpu_count))
주석 추가하였습니다. (현재가 최선입니다)

2020-05-21 08:56 UTC, leeopop commented on build.rs
> +/// 1. If `SYSTEM_CPU_COUNT` env is set, use this value.
두 라이브러리의 기능은 다르지만 해결하고자 하는 목표가 같으므로 (static config 를 생성) 일단은 유지하려고 합니다.

2020-05-21 09:59 UTC, leeopop commented on build.rs
> +        let is_end = out_dir.file_name().unwrap() == "target";
더 나은 방법 (dependency 는 조금 더 많지만)을 찾아서 반영하고 링크 달았습니다.

2020-05-21 10:03 UTC, jeehoonkang commented on build.rs
> +/// 1. If `SYSTEM_CPU_COUNT` env is set, use this value.
- 저는 `SYSTEM_CPU_COUNT`를 쓰지 말자는 의견이었습니다.
- 만일 environment variable을 지정하고 싶다면, 모든 environment variable에 대해 constant를 만들어주는 것도 고려해봄직합니다.

2020-05-21 10:04 UTC, jeehoonkang commented on Cargo.toml
> +authors = ["Keunhong Lee <dlrmsghd@gmail.com>", "ANLAB Support <support@an.kaist.ac.kr>"]
- 만일 그러고 싶다면 "ANLAB Support"가 아니라 "ANLAB"이 되어야하지 않을까 합니다.
- 혹은 근홍님 이메일에 기관을 명시하거나..

2020-05-21 10:09 UTC, leeopop commented on Cargo.toml
> +authors = ["Keunhong Lee <dlrmsghd@gmail.com>", "ANLAB Support <support@an.kaist.ac.kr>"]
전자로 반영하였습니다.

2020-05-21 10:10 UTC, leeopop commented on build.rs
> +/// 1. If `SYSTEM_CPU_COUNT` env is set, use this value.
앗 이해했습니다.

2020-05-21 10:12 UTC, leeopop commented on build.rs
> +/// 1. If `SYSTEM_CPU_COUNT` env is set, use this value.
모든 env 로 세팅하기에는 `rerun-if-env-changed` cargo 옵션이 원활이 동작하지 못할 것 같아서 모두 제거하는게 나을 것 같습니다 (추후에 env를 추가했을 때 build.rs 가 정상적으로 불리지 못할 수 있음)

2020-05-21 10:15 UTC, leeopop reviewed
@jeehoonkang 현재까지 코멘트 주신 사항 모두 반영하였습니다.

2020-05-21 10:40 UTC, jeehoonkang approved these changes
I'm mostly happy with this PR.  Please look at my comments and merge it.

2020-05-21 10:40 UTC, jeehoonkang commented on Cargo.toml
> +num_cpus = "^1.0"
Toml에서 caret은 없어도 됩니다.

2020-05-21 10:40 UTC, jeehoonkang commented on build.rs
> +/// 1. If `SYSTEM_CPU_COUNT` env is set, use this value.
네 일단 `SYSTEM_CPU_COUNT`를 제거합시다.  주석에 남아있는 것 같아요.

2020-05-21 10:43 UTC, leeopop commented
마지막 수정사항 모두 반영하였습니다.
머지하고 FPS에 반영하도록 하겠습니다.

2020-05-21 10:43 UTC, leeopop commented
bors r+

2020-05-21 10:47 UTC, merged